### ISSUE TITLE
Getting ERR! iotivity-node@1.0.0-4 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by vundisrikar** [01org/iot-rest-api-server#35]
I am getting error while running npm install in base directory of iot-rest-api-server.
[npm-debug.log.tar.gz](https://github.com/01org/iot-rest-api-server/files/424192/npm-debug.log.tar.gz)

**Comment by nagineni** [comment]
Thanks for the report. Looks like you are using the old version which is dependent on old iotivity-node@1.0.0-4. Can you try with the latest from the master that pulls the iotivity-node@1.1.0-5?

Old version(s) of iotivity-node has a build issue due to the broken IoTivity dependency.

**Comment by vundisrikar** [comment]
Above change has solved my issue.
