### ISSUE TITLE
The 'di' properties of resources on a single device changing by JS scripts in 1.1.1-3

### ISSUE THREAD

**Issue by ttzeng** [01org/iot-rest-api-server#42]
The 'di' properties in the REST API server report will vary by the server scripts in 1.1.1-3, even they are on the same device. For example, resources '/a/led' and '/a/led1' are hosted by different scripts, their 'di' are different; however if resources '/a/led1' and '/a/led2' are hosted by a single parameterised script, they will have the same 'di' property. What is the right behavior?

Test result 1: the [first server report](https://github.com/01org/iot-rest-api-server/files/653851/rest-server-report.txt)
Test result 2: the [server report after software reboot](https://github.com/01org/iot-rest-api-server/files/653852/rest-server-report-after-reboot.txt)
Test result 3: the [server report after hardware power recycling](https://github.com/01org/iot-rest-api-server/files/653855/rest-server-report-after-repower.txt)

**Comment by nagineni** [comment]
Registering resources from different scripts will contain different `di` property and that will be persistent across instantiations of a script according to the iotivity and iotivity-node wiki. 

https://wiki.iotivity.org/faq_s
https://github.com/otcshare/iotivity-node#provisioning-and-device-id-persistence

**Comment by nagineni** [comment]
The actual behaviour is same as explained the wikis, so closing this.

**Comment by ttzeng** [comment]
The wikis specify the device should persist the device ID across instances, but never mention the relationship between the device ID and the implementation. In the OIC Security spec 1.1, section 7.1:
"Each OIC device, which is a logical device, is identified with a device ID."
"OIC devices SHALL identified by a DeviceID value that is established as part of device on
boarding..... **Device IDs shall be unique within the scope of operation of the corresponding OIC network,** and should be universally unique. Device ID uniqueness within the network should enforced at device on boarding." 
"An OIC device maintains its device ID in the **/oic/sec/doxm** resource."
No mater devices are registered with different scripts or a parameterized script, it looks like they all have a associated /oic/sec/doxm resource, should we keep all the device IDs unique according to the spec?
