### ISSUE TITLE
The `iot-rest-api-server` interferes with the `snap` tool and daemon

### ISSUE THREAD

**Issue by gvancuts** [01org/iot-rest-api-server#47]
Some `snap` commands do not work anymore after installing the `iot-rest-api-server` snap. I suspect this is caused by the use of port 80 in the snap (I will try a quick test replacing the port number later).

How to reproduce the issue:
```
# Build the snap
$ snapcraft
# Install it
$ sudo snap install ./iot-rest-api-server_0.1_amd64.snap --devmode
# Try a snap command
$ snap list
# It throws the following error:
error: cannot list snaps: cannot communicate with server: Get http://localhost/v2/snaps: dial unix /run/snapd.socket: connect: connection refused
# Disable the snap
$ sudo snap disable iot-rest-api-server
# Try again
$ snap list
# It works as expected
```

**Comment by gvancuts** [comment]
I have confirmed that using a different port in the `iot-rest-api-server` snap makes the problem go away.

I have used:
```
diff --git a/snapcraft.yaml b/snapcraft.yaml
index ac87f17..1296037 100644
--- a/snapcraft.yaml
+++ b/snapcraft.yaml
@@ -7,9 +7,8 @@ grade: devel
 
 apps:
   start-iot-rest-api-server:
-    command: node $SNAP/lib/node_modules/iot-rest-api-server/index.js --port 80
+    command: node $SNAP/lib/node_modules/iot-rest-api-server/index.js --port 8000
     daemon: simple
-    restart-condition: always
     plugs: [ network-bind ]
 
 parts:
```

If you believe this is the right approach to fix it, I can create a PR.

**Comment by poussa** [comment]
Hmm, I don't have any issues with the snap commands and iot-rest-api-server running on port 80.

**Comment by gvancuts** [comment]
OK... I don't anymore either. There was an update that I installed yesterday, perhaps it was a side-effect of this, a bug that got fixed or my mistake.... I'll close this as I can't reproduce it either.
