### ISSUE TITLE
REST API server should handle URL with a trailing slash

### ISSUE THREAD

**Issue by qiuzhong** [01org/iot-rest-api-server#52]
Steps:
1. Launch an [OCF server](https://github.com/01org/SmartHome-Demo/tree/master/ocf-servers/js-servers) and the iot-rest-api-server service
```
# node led.js &
# systemctl start iot-rest-api-server
```

2. Send requests to discover OCF devices
```
# curl http://127.0.0.1:8000/api/oic/d
[{"di":"63653237-3561-3632-2d64-3339622d3438","n":"Smart Home LED","icv":"1.0.0"}]
# curl http://127.0.0.1:8000/api/oic/d?di=63653237-3561-3632-2d64-3339622d3438
[{"di":"63653237-3561-3632-2d64-3339622d3438","n":"Smart Home LED","icv":"1.0.0"}]
```

Here if there is a trailing slash, the output will be
```
# curl http://127.0.0.1:8000/api/oic/d/?di=63653237-3561-3632-2d64-3339622d3438
{"properties":{"id":"led","value":false}}
```
It returns the properties of the OCF resource. Seems if there is a trailing slash, the URL semantics will be totally different.
Does this API spec requires "strict routing" <strong>/api/oic/d</strong>? If not, the trailing slash case should be handled.

Discovering OCF platforms/resources also has the same problem.

**Comment by nagineni** [comment]
> `# curl http://127.0.0.1:8000/api/oic/d/?di=63653237-3561-3632-2d64-3339622d3438`
{"properties":{"id":"led","value":false}}

We support URLs without trailing slash, so the above request should through 404 instead of LED resource properties. Please check once again and confirm.

Here is the output I'm getting:
```
$ curl http://127.0.0.1:8000/api/oic/d/?di=dcb5f010-0cc1-43a9-b25d-470392e6058a
Resource retrieve failed: Resource not found
HTTP: 404
```

**Comment by qiuzhong** [comment]
Verified. This issue is not reproduced on the latest iot-rest-api-server master branch now. 

It's reported before the <code>v0.2.0</code> release. The iot-rest-api-server was the <code>v0.1.0</code> version in Ostro image#519 at that time. Now the iot-rest-api-server has been updated to <code>v0.2.0</code> in IoT-Refkit image. So this issue is invalid and let's close it.
