### ISSUE TITLE
REST API not finding resources

### ISSUE THREAD

**Issue by uhofemei** [01org/iot-rest-api-server#56]
Hi, 

I installed iot-rest-api-server using npm install on Ubuntu 16.04. The issue I’m having is that I don’t see any of the resources appear in the REST API page.

I noticed the default service file is using user and group being restful. As I don't have this user on my system, it to my unprivileged user account. OCF servers on another host are running as root. Could this be a permission problem?

**Comment by nagineni** [comment]
'restful' user is used only on yocto based images to run the server under non-root user. So, it doesn't require if you are running the server on Ubuntu. Also, running OCF servers as root should be okay.

**Comment by nagineni** [comment]
I tried here on Ubuntu 16.04 and it's working fine for me. 

Is there any firewall running in your env? If yes, it might be blocking the iotivity traffic. Please check and confirm.

**Comment by uhofemei** [comment]
I'm not longer able to reproduce the issue. The REST API server is finding the OCF sensor resources fine. Closing the issue.
