### ISSUE TITLE
/api/oic/d returns an incomplete device object

### ISSUE THREAD

**Issue by qiuzhong** [01org/iot-rest-api-server#68]
## Description:
When there is no OCF server running, `/api/oic/d` still returns a device object. 
```
$ curl --noproxy "*" http://10.239.115.101:8000/api/oic/d
[{"di":"cfc5ff9a-0e55-4443-92ee-2de4df834aed"}] 
```

Meanwhile, this object contains only **di** property. This doesn't correspond to the REST API spec. The [REST API spec](https://github.com/01org/iot-rest-api-server/blob/master/doc/oic.wk.d.json#L33) requires `/api/oic/d` requests return objects that contain the `"n", "di", "icv" ` properties:

>   "required": [ "n", "di", "icv" ]

## Envrionment:
* [Intel-IoT-Refkit gateway image build#211](http://iot-ref-kit.ostc.intel.com/download/builds/intel-iot-refkit_master/2017-06-19_03-13-06-build-211/images/intel-corei7-64/)
* iot-rest-api-server: v0.4.0
* iotivity-node: v1.2.1-1

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced when using #78 to verify it.
Right device object is returned when running iot-rest-api-server.
