### ISSUE TITLE
Error while querying sensor resource

### ISSUE THREAD

**Issue by uhofemei** [01org/iot-rest-api-server#72]
Hi Babu,

trying to use REST API version 0.6.0, I observe the following error message in docker logs if I attempt access a resource directly. Could you please take a look? Thanks.

```
ClientResource {
  properties: {},
  resourcePath: '/a/temperature',
  deviceId: 'eda7d024-67cb-465e-97ab-7bb5e4d349a9',
  interfaces: [ 'oic.if.baseline' ],
  resourceTypes: [ 'oic.r.temperature' ],
  discoverable: true,
  slow: false,
  secure: false,
  observable: true,
  active: false,
  _events: { newListener: [Function], removeListener: [Function] },
  _eventsCount: 2 }
{"di":"eda7d024-67cb-465e-97ab-7bb5e4d349a9","links":[{"href":"/a/temperature","rt":["oic.r.temperature"],"if":["oic.if.baseline"],"p":{"bm":3,"secure":false}}]}
No request handler for /favicon.ico
GET /api/oic/a/temperature?di=eda7d024-67cb-465e-97ab-7bb5e4d349a9 (fd: 23)
/opt/SmartHome-Demo/gateway/node_modules/iotivity-node/lib/payload.js:208
					( payload.values.anchor.match( uuidRegex ) || [] )[ 0 ] );
					                       ^

TypeError: Cannot read property 'match' of undefined
    at Object.payloadUtils.processGetOicRes (/opt/SmartHome-Demo/gateway/node_modules/iotivity-node/lib/payload.js:208:29)
    at Object._.extend.createAnswer (/opt/SmartHome-Demo/gateway/node_modules/iotivity-node/lib/Client.js:490:36)
    at Immediate._onImmediate (/opt/SmartHome-Demo/gateway/node_modules/iotivity-node/lib/Client.js:158:25)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[root@gateway1 ~]# 
```

**Comment by gvancuts** [comment]
Just to add, based on my conversation with @uhofemei , the OCF servers that running IoTivity 1.2.x. Is that correct @uhofemei ?

**Comment by nagineni** [comment]
This is not related to the REST API server.  TypeError is from iotivity-node when the SmartHome gateway is running. 

```
/opt/SmartHome-Demo/gateway/node_modules/iotivity-node/lib/payload.js:208
					( payload.values.anchor.match( uuidRegex ) || [] )[ 0 ] );
```

'payload.values.anchor' property seems to be undefined for some reason. I will fix this in iotivity-node.

**Comment by uhofemei** [comment]
Could it be that the rest-api-server is not pulling Gabriel’s latest commit to iotivity-node as a dependency when the container is built?

**Comment by nagineni** [comment]
> Could it be that the rest-api-server is not pulling Gabriel’s latest commit to iotivity-node as a dependency when the container is built?

As I said before, this bug is nothing to do with the REST API server. The error logs are from the SmartHome gateway server.

**Comment by uhofemei** [comment]
I understand that. I'm asking if it's based on the fact that one component depends on the other to be updated :-)

**Comment by nagineni** [comment]
> Just to add, based on my conversation with @uhofemei , the OCF servers that running IoTivity 1.2.x. Is that correct @uhofemei ?

@uhofemei are you running OCF servers  based on IoTivity 1.2.x and gateway server on IoTivity 1.3.0?

**Comment by uhofemei** [comment]
I was. I reverted to rest api 0.5.0, which fixes things for the demo.

**Comment by nagineni** [comment]
Very confused about the demo setup :). Anycase, make sure that you use the OCF servers, gateway and iot-rest-api-server are based on the same version of iotivity-node.

**Comment by nagineni** [comment]
I can reproduce this if I run temperature.js server based **iotivity 1.2.x** and the SmartHome gateway based on **iotivity 1.3.0**.

**Comment by nagineni** [comment]
Running server and client on different version of iotivity is not recommended. Not to see this error, please use the same version in both server and client side.

**Comment by uhofemei** [comment]
The error came about due to the Docker gateway image built with this [Dockerfile](https://github.com/uhofemei/SmartHome-Demo/blob/master/gateway/Dockerfile) still ends up with a version of iotivity-node that doesn't allow access to the REST API resource. I see in the package.json file in your [repo](https://github.com/01org/iot-rest-api-server/blob/master/package.json) you pull iotivity-node version 1.3.0-0 Gabriel since then submitted an updated to 1.3.0-1. https://github.com/otcshare/iotivity-node/commit/52421883aa322a98b5ebe492700a0609e68af592 Could this be the issue?

**Comment by gvancuts** [comment]
> The error came about due to the Docker gateway image built with this Dockerfile still ends up with a version of iotivity-node that doesn't allow access to the REST API resource.
It works fine with that version too but you need to make sure that the iotivity-node stack running on the OCF servers (resources) is of the same version (i.e. 1.3.x). If you need to expose OCF servers (resources) running on IoTivity 1.2.x, you need to downgrade the iot-rest-api-server to 0.5.0 in the package.json file and rebuild the Docker container.

**Comment by uhofemei** [comment]
Got it. I have downgraded to 0.5.0 as I don't have Edison images with 1.3.0 readily available.

**Comment by nagineni** [comment]
> Got it. I have downgraded to 0.5.0 as I don't have Edison images with 1.3.0 readily available.

Nice! Make sure that the SmartHome gateway server (i.e rules engine) also running on IoTivity 1.2.x. Basically you need to use the old commit (https://github.com/01org/SmartHome-Demo/commit/4ad6c9e17c32cd5ef886b2ea144317c28e83dd9e) of SmartHome repo.
