### ISSUE TITLE
Can't find command "iot-rest-api-server" following steps in README file

### ISSUE THREAD

**Issue by wanghongjuan** [01org/iot-rest-api-server#79]
According to this [step](https://github.com/01org/iot-rest-api-server#global-install), after running `npm install -g iot-rest-api-server`, the server can be started with `$ iot-rest-api-server`, but when running this command, I got information "iot-rest-api-server: command not found".
The same issue exists in sections [`Usage`](https://github.com/01org/iot-rest-api-server#usage) and [`Command line Options`](https://github.com/01org/iot-rest-api-server#command-line-options).

**Comment by nagineni** [comment]
We have not published the new version with the bin script to NPM yet.  For now, you can test it by running 'npm install -g'  in the git cloned repo .

**Comment by wanghongjuan** [comment]
I tried with git clone way and launched the server with `npm start` or `./bin/iot-rest-api-server.js` successfully. But this README is confused, will you update this file?
